apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: demo-ns
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      serviceAccountName: priviliged-demo-user
      containers:
      - name: demo-app
        image: mcdrums/demo-app:1.0
        ports:
        - containerPort: 8080
